// <auto-generated />
// Generated by tools/generate-known-entities.ps1 from data/known-entities.tsv
// and validated against data/entity-mappings.tsv. Do not edit by hand.

using System;

namespace OrbModding.Common;

internal readonly struct AlchemyInstanceListVariableContract { }
internal readonly struct AlchemyRecipeListVariableContract { }
internal readonly struct AlchemyTypeSOContract { }
internal readonly struct PlotNodeActionInstanceListVariableContract { }
internal readonly struct PlotNodeActionSOContract { }
internal readonly struct PlotNodeSOContract { }
internal readonly struct ScalingWeightSOContract { }
internal readonly struct TreasurePoolSOContract { }
internal readonly struct UpgradeSOContract { }
internal readonly struct ViewSOContract { }

internal readonly struct KnownEntity<TContract>
{
    public KnownEntity(Guid uuid, string managedTypeName, string diagnosticName)
    {
        Uuid = uuid;
        ManagedTypeName = managedTypeName;
        DiagnosticName = diagnosticName;
    }

    public Guid Uuid { get; }
    public string ManagedTypeName { get; }
    public string DiagnosticName { get; }
}

internal static class KnownEntities
{
    public static readonly KnownEntity<AlchemyInstanceListVariableContract> ActiveConcepts = new(new Guid("9121924d-2692-428b-9599-165224ccd899"), "AlchemyInstanceListVariable", "ActiveConcepts");
    public static readonly KnownEntity<PlotNodeActionInstanceListVariableContract> ActivePlotNodeActions = new(new Guid("70871e86-100b-4ae0-ba9b-fc96e09b7e1f"), "PlotNodeActionInstanceListVariable", "ActivePlotNodeActions");
    public static readonly KnownEntity<AlchemyTypeSOContract> Alchemy = new(new Guid("f9c93e42-e9e8-4fe3-a1f3-5aec5430b5c2"), "AlchemyTypeSO", "Alchemy");
    public static readonly KnownEntity<ViewSOContract> AlchemyScreen = new(new Guid("3ae45ec0-4449-4903-b3d0-b5182e03dca3"), "ViewSO", "ScreenAlchemy");
    public static readonly KnownEntity<AlchemyTypeSOContract> Brewing = new(new Guid("d2947f69-d989-465d-8159-204285ed57be"), "AlchemyTypeSO", "Brewing");
    public static readonly KnownEntity<ScalingWeightSOContract> CompletionScalingWeight = new(new Guid("be446180-242f-40d2-910e-91e735fc20ad"), "ScalingWeightSO", "SpecialScaling");
    public static readonly KnownEntity<AlchemyRecipeListVariableContract> ConceptRecipes = new(new Guid("c8ff8e01-c042-49c2-86a2-e374f82c280c"), "AlchemyRecipeListVariable", "ConceptRecipes");
    public static readonly KnownEntity<AlchemyTypeSOContract> Conceptualization = new(new Guid("69842862-dfce-4a9e-a73b-f757c72e49dc"), "AlchemyTypeSO", "Conceptualization");
    public static readonly KnownEntity<AlchemyTypeSOContract> Dismantle = new(new Guid("7b89d22c-75ae-4945-9356-833382c9a167"), "AlchemyTypeSO", "Dismantle");
    public static readonly KnownEntity<AlchemyTypeSOContract> Enchantment = new(new Guid("2ffcbbc4-49a7-45db-b3ae-4a3c57362255"), "AlchemyTypeSO", "Enchantment");
    public static readonly KnownEntity<PlotNodeActionSOContract> FruitTreeCollect = new(new Guid("60ea60a2-44e9-41c2-86d6-3935fae0b647"), "PlotNodeActionSO", "PNAFruitTreeCollect");
    public static readonly KnownEntity<PlotNodeSOContract> FruitTreePlot = new(new Guid("6782dd13-e229-4385-a1aa-8ed86e6ea1ed"), "PlotNodeSO", "PlotFruitTree");
    public static readonly KnownEntity<TreasurePoolSOContract> FruitTreeRewardPool = new(new Guid("b3ab80f0-80c7-41d4-b4c7-f34c3e909104"), "TreasurePoolSO", "FruitTreasurePool");
    public static readonly KnownEntity<ViewSOContract> MagicSpellbook = new(new Guid("ca934900-0253-4f71-93e9-733fb91132b7"), "ViewSO", "MagicSpellbook");
    public static readonly KnownEntity<ViewSOContract> MasteriesEnabled = new(new Guid("07dfae7e-76b9-4b38-bf81-38abc40b9ed7"), "ViewSO", "MasteriesEnabled");
    public static readonly KnownEntity<AlchemyTypeSOContract> Reductive = new(new Guid("47b787b9-d4cd-43c8-a7e3-63a1e4e0ae94"), "AlchemyTypeSO", "Reductive");
    public static readonly KnownEntity<AlchemyTypeSOContract> Refinement = new(new Guid("32b6b099-19f2-4470-b47b-6c2a8b0388e1"), "AlchemyTypeSO", "Refinement");
    public static readonly KnownEntity<AlchemyTypeSOContract> Reflective = new(new Guid("8f258dcc-c39a-4d64-b915-4239e746c49d"), "AlchemyTypeSO", "Reflective");
    public static readonly KnownEntity<AlchemyTypeSOContract> Transmutation = new(new Guid("b42c6192-7d9b-40d0-aa40-3d46a9348e52"), "AlchemyTypeSO", "Transmutation");
    public static readonly KnownEntity<PlotNodeActionSOContract> TreasureTreeCollect = new(new Guid("3eb68f6f-c2f2-405a-88d2-e5c80345aeb4"), "PlotNodeActionSO", "PNATreasureTreeCollect");
    public static readonly KnownEntity<PlotNodeSOContract> TreasureTreePlot = new(new Guid("2d41cfc1-bffa-43b5-b3a8-5e4d5ad85434"), "PlotNodeSO", "PlotTreasureTree");
    public static readonly KnownEntity<TreasurePoolSOContract> TreasureTreeRewardPool = new(new Guid("1a370ff9-fea7-4a2a-bca7-57fdb2862356"), "TreasurePoolSO", "CoreTreasurePool");
    public static readonly KnownEntity<UpgradeSOContract> UnlockLevelAllSpells = new(new Guid("b5efd19a-9655-4359-ad27-f391bb86c2e4"), "UpgradeSO", "UnlockLevelAllSpells");
    public static readonly KnownEntity<ViewSOContract> WorkshopArtifact = new(new Guid("668a2a7a-468f-4e0e-b182-979b12a4b0ad"), "ViewSO", "WorkshopArtifact");
}
