param(
    [switch] $Verify,
    [string] $CanonicalPath,
    [string] $SelectionPath,
    [string] $OutputPath
)

$ErrorActionPreference = 'Stop'

$repositoryRoot = Split-Path -Parent $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($CanonicalPath)) { $CanonicalPath = Join-Path $repositoryRoot 'data/entity-mappings.tsv' }
if ([string]::IsNullOrWhiteSpace($SelectionPath)) { $SelectionPath = Join-Path $repositoryRoot 'data/known-entities.tsv' }
if ([string]::IsNullOrWhiteSpace($OutputPath)) { $OutputPath = Join-Path $repositoryRoot 'src/OrbModding.Common/KnownEntities.Generated.cs' }
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

function Read-StrictTsv([string] $path, [string] $header) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Required input does not exist: $path"
    }
    $lines = [System.IO.File]::ReadAllLines($path, [System.Text.Encoding]::UTF8)
    if ($lines.Count -eq 0 -or $lines[0] -cne $header) {
        throw "Unexpected TSV header in ${path}: expected '$header'"
    }
    return $lines
}

$canonicalLines = Read-StrictTsv $CanonicalPath "id`tname`ttype"
$canonicalById = @{}
for ($index = 1; $index -lt $canonicalLines.Count; $index++) {
    $parts = $canonicalLines[$index].Split("`t")
    if ($parts.Count -ne 3) { throw "Invalid canonical mapping at line $($index + 1)" }
    $parsed = [Guid]::Empty
    if (-not [Guid]::TryParseExact($parts[0], 'D', [ref] $parsed)) {
        throw "Invalid canonical UUID at line $($index + 1): $($parts[0])"
    }
    $id = $parsed.ToString('D')
    if ($canonicalById.ContainsKey($id)) { throw "Duplicate canonical UUID: $id" }
    $canonicalById.Add($id, [pscustomobject]@{ id = $id; name = $parts[1]; type = $parts[2] })
}

$selectionLines = Read-StrictTsv $SelectionPath "symbol`tid`tname`ttype"
$records = [System.Collections.Generic.List[object]]::new()
$symbols = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
$selectedIds = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
for ($index = 1; $index -lt $selectionLines.Count; $index++) {
    $parts = $selectionLines[$index].Split("`t")
    if ($parts.Count -ne 4) { throw "Invalid known-entity selection at line $($index + 1)" }
    if ($parts[0] -notmatch '^[A-Z][A-Za-z0-9]*$') { throw "Invalid generated symbol '$($parts[0])'" }
    if ($parts[3] -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') { throw "Unsupported generated managed type '$($parts[3])' for $($parts[0])" }
    if (-not $symbols.Add($parts[0])) { throw "Duplicate generated symbol: $($parts[0])" }
    $parsed = [Guid]::Empty
    if (-not [Guid]::TryParseExact($parts[1], 'D', [ref] $parsed)) {
        throw "Invalid selected UUID for $($parts[0]): $($parts[1])"
    }
    $id = $parsed.ToString('D')
    if (-not $selectedIds.Add($id)) { throw "Duplicate selected UUID: $id" }
    if (-not $canonicalById.ContainsKey($id)) { throw "Selected UUID is absent from canonical mappings: $id" }
    $canonical = $canonicalById[$id]
    if ($parts[2] -cne $canonical.name -or $parts[3] -cne $canonical.type) {
        throw "Canonical mapping drift for $($parts[0]): expected '$($parts[2])/$($parts[3])', found '$($canonical.name)/$($canonical.type)'"
    }
    $records.Add([pscustomobject]@{ symbol = $parts[0]; id = $id; name = $parts[2]; type = $parts[3] })
}

if ($records.Count -eq 0) { throw 'At least one explicitly selected known entity is required.' }
$records.Sort([System.Comparison[object]] {
    param($left, $right)
    [StringComparer]::Ordinal.Compare([string] $left.symbol, [string] $right.symbol)
})
$managedTypes = [System.Collections.Generic.List[string]]::new()
foreach ($record in $records) {
    if (-not $managedTypes.Contains($record.type)) { $managedTypes.Add($record.type) }
}
$managedTypes.Sort([StringComparer]::Ordinal)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('// <auto-generated />')
$lines.Add('// Generated by tools/generate-known-entities.ps1 from data/known-entities.tsv')
$lines.Add('// and validated against data/entity-mappings.tsv. Do not edit by hand.')
$lines.Add('')
$lines.Add('using System;')
$lines.Add('')
$lines.Add('namespace OrbModding.Common;')
$lines.Add('')
foreach ($managedType in $managedTypes) {
    $lines.Add("internal readonly struct $($managedType)Contract { }")
}
$lines.Add('')
$lines.Add('internal readonly struct KnownEntity<TContract>')
$lines.Add('{')
$lines.Add('    public KnownEntity(Guid uuid, string managedTypeName, string diagnosticName)')
$lines.Add('    {')
$lines.Add('        Uuid = uuid;')
$lines.Add('        ManagedTypeName = managedTypeName;')
$lines.Add('        DiagnosticName = diagnosticName;')
$lines.Add('    }')
$lines.Add('')
$lines.Add('    public Guid Uuid { get; }')
$lines.Add('    public string ManagedTypeName { get; }')
$lines.Add('    public string DiagnosticName { get; }')
$lines.Add('}')
$lines.Add('')
$lines.Add('internal static class KnownEntities')
$lines.Add('{')
foreach ($record in $records) {
    $lines.Add("    public static readonly KnownEntity<$($record.type)Contract> $($record.symbol) = new(new Guid(`"$($record.id)`"), `"$($record.type)`", `"$($record.name)`");")
}
$lines.Add('}')
$generated = [string]::Join("`n", $lines) + "`n"

if ($Verify) {
    if (-not (Test-Path -LiteralPath $OutputPath -PathType Leaf)) {
        throw "Generated output is missing: $OutputPath"
    }
    $actual = [System.IO.File]::ReadAllText($OutputPath, [System.Text.Encoding]::UTF8).Replace("`r`n", "`n")
    if ($actual -cne $generated) {
        throw "Generated output is stale. Run tools/generate-known-entities.ps1 and commit the result."
    }
    Write-Host "Verified $($records.Count) generated known entities."
    exit 0
}

[System.IO.File]::WriteAllText($OutputPath, $generated, $utf8NoBom)
Write-Host "Generated $($records.Count) known entities: $OutputPath"
