#!/usr/bin/env bash
# Generates or verifies src/OrbModding.Common/KnownEntities.Generated.cs from
# data/known-entities.tsv, validated against data/entity-mappings.tsv.
# Behavioral mirror of tools/generate-known-entities.ps1 (same validation, same bytes),
# so non-Windows builds do not require PowerShell. Portable: stock macOS bash 3.2 + awk.
set -euo pipefail
export LC_ALL=C

VERIFY=0
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPOSITORY_ROOT="$(dirname "$SCRIPT_DIR")"
CANONICAL_PATH="$REPOSITORY_ROOT/data/entity-mappings.tsv"
SELECTION_PATH="$REPOSITORY_ROOT/data/known-entities.tsv"
OUTPUT_PATH="$REPOSITORY_ROOT/src/OrbModding.Common/KnownEntities.Generated.cs"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -Verify) VERIFY=1; shift ;;
        -CanonicalPath) CANONICAL_PATH="$2"; shift 2 ;;
        -SelectionPath) SELECTION_PATH="$2"; shift 2 ;;
        -OutputPath) OUTPUT_PATH="$2"; shift 2 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

fail() { echo "$1" >&2; exit 1; }
[[ -f $CANONICAL_PATH ]] || fail "Required input does not exist: $CANONICAL_PATH"
[[ -f $SELECTION_PATH ]] || fail "Required input does not exist: $SELECTION_PATH"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/known-entities.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT
CANONICAL_NORM="$TMP_DIR/canonical.norm"
SELECTION_NORM="$TMP_DIR/selection.norm"
GENERATED_FILE="$TMP_DIR/generated.cs"

# Validates and normalizes the canonical mapping TSV to "id\tname\ttype" records.
awk '
function die(message) { print message > "/dev/stderr"; exit 1 }
function valid_guid(s,   t) {
    if (length(s) != 36) return 0
    if (substr(s, 9, 1) != "-" || substr(s, 14, 1) != "-" || substr(s, 19, 1) != "-" || substr(s, 24, 1) != "-") return 0
    t = s
    gsub(/[0-9a-f]/, "", t)
    return t == "----"
}
NR == 1 {
    if ($0 != "id\tname\ttype") die("Unexpected TSV header in " FILENAME ": expected \x27id\tname\ttype\x27")
    next
}
{
    line = $0
    sub(/\r$/, "", line)
    count = split(line, field, "\t")
    if (count != 3) die("Invalid canonical mapping at line " NR)
    id = tolower(field[1])
    if (!valid_guid(id)) die("Invalid canonical UUID at line " NR ": " field[1])
    if (id in seen) die("Duplicate canonical UUID: " id)
    seen[id] = 1
    printf "%s\t%s\t%s\n", id, field[2], field[3]
}
' "$CANONICAL_PATH" > "$CANONICAL_NORM"

# Validates the selection TSV against the canonical mapping and emits "symbol\ttype\tid\tname".
awk '
function die(message) { print message > "/dev/stderr"; exit 1 }
function valid_guid(s,   t) {
    if (length(s) != 36) return 0
    if (substr(s, 9, 1) != "-" || substr(s, 14, 1) != "-" || substr(s, 19, 1) != "-" || substr(s, 24, 1) != "-") return 0
    t = s
    gsub(/[0-9a-f]/, "", t)
    return t == "----"
}
NR == FNR {
    canonical_name[$1] = $2
    canonical_type[$1] = $3
    next
}
FNR == 1 {
    if ($0 != "symbol\tid\tname\ttype") die("Unexpected TSV header in " FILENAME ": expected \x27symbol\tid\tname\ttype\x27")
    next
}
{
    line = $0
    sub(/\r$/, "", line)
    count = split(line, field, "\t")
    if (count != 4) die("Invalid known-entity selection at line " FNR)
    symbol = field[1]
    if (symbol !~ /^[A-Z][A-Za-z0-9]*$/) die("Invalid generated symbol \x27" symbol "\x27")
    if (field[4] !~ /^[A-Za-z_][A-Za-z0-9_]*$/) die("Unsupported generated managed type \x27" field[4] "\x27 for " symbol)
    if (symbol in seen_symbol) die("Duplicate generated symbol: " symbol)
    seen_symbol[symbol] = 1
    id = tolower(field[2])
    if (!valid_guid(id)) die("Invalid selected UUID for " symbol ": " field[2])
    if (id in seen_id) die("Duplicate selected UUID: " id)
    seen_id[id] = 1
    if (!(id in canonical_name)) die("Selected UUID is absent from canonical mappings: " id)
    if (field[3] != canonical_name[id] || field[4] != canonical_type[id]) {
        die("Canonical mapping drift for " symbol ": expected \x27" field[3] "/" field[4] "\x27, found \x27" canonical_name[id] "/" canonical_type[id] "\x27")
    }
    printf "%s\t%s\t%s\t%s\n", symbol, field[4], id, field[3]
}
' "$CANONICAL_NORM" "$SELECTION_PATH" > "$SELECTION_NORM"

[[ -s $SELECTION_NORM ]] || fail 'At least one explicitly selected known entity is required.'
RECORD_COUNT="$(wc -l < "$SELECTION_NORM" | tr -d ' ')"

sort "$SELECTION_NORM" > "$TMP_DIR/records.sorted"
cut -f2 "$SELECTION_NORM" | sort -u > "$TMP_DIR/types.sorted"

{
    printf '%s\n' '// <auto-generated />'
    printf '%s\n' '// Generated by tools/generate-known-entities from data/known-entities.tsv'
    printf '%s\n' '// and validated against data/entity-mappings.tsv. Do not edit by hand.'
    printf '\n'
    printf '%s\n' 'using System;'
    printf '\n'
    printf '%s\n' 'namespace OrbModding.Common;'
    printf '\n'
    while IFS= read -r managed_type; do
        printf 'internal readonly struct %sContract { }\n' "$managed_type"
    done < "$TMP_DIR/types.sorted"
    printf '\n'
    printf '%s\n' 'internal readonly struct KnownEntity<TContract>'
    printf '%s\n' '{'
    printf '%s\n' '    public KnownEntity(Guid uuid, string managedTypeName, string diagnosticName)'
    printf '%s\n' '    {'
    printf '%s\n' '        Uuid = uuid;'
    printf '%s\n' '        ManagedTypeName = managedTypeName;'
    printf '%s\n' '        DiagnosticName = diagnosticName;'
    printf '%s\n' '    }'
    printf '\n'
    printf '%s\n' '    public Guid Uuid { get; }'
    printf '%s\n' '    public string ManagedTypeName { get; }'
    printf '%s\n' '    public string DiagnosticName { get; }'
    printf '%s\n' '}'
    printf '\n'
    printf '%s\n' 'internal static class KnownEntities'
    printf '%s\n' '{'
    while IFS=$'\t' read -r symbol type id name; do
        printf '    public static readonly KnownEntity<%sContract> %s = new(new Guid("%s"), "%s", "%s");\n' \
            "$type" "$symbol" "$id" "$type" "$name"
    done < "$TMP_DIR/records.sorted"
    printf '%s\n' '}'
} > "$GENERATED_FILE"

if [[ $VERIFY -eq 1 ]]; then
    [[ -f $OUTPUT_PATH ]] || fail "Generated output is missing: $OUTPUT_PATH"
    if ! tr -d '\r' < "$OUTPUT_PATH" | cmp -s - "$GENERATED_FILE"; then
        fail "Generated output is stale. Run tools/generate-known-entities and commit the result."
    fi
    echo "Verified ${RECORD_COUNT} generated known entities."
    exit 0
fi

cp "$GENERATED_FILE" "$OUTPUT_PATH"
echo "Generated ${RECORD_COUNT} known entities: $OUTPUT_PATH"
